routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('product', 'ProductsController');

Route::group(['prefix' => 'filter'], function() {
    Route::get('/', 'ProductFilterController@index')->name('index');
    Route::get('/search', 'ProductFilterController@search')->name('search');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
    protected $fillable = ['title', 'price'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductFilterController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Redis;

class ProductFilterController extends Controller
{
    public function index()
    {
        return view('product.index');
    }
    public function search(Request $request)
    {
        $cacheKey = hash('ripemd160', implode(',', array_values($request->input())));

        $products = Cache::remember($cacheKey, 10000, function () use ($request) {
            $query = Product::query();
            $page = $request->get('page');
            $pageSize = $request->get('page_size');

            if ($request->has('title') && $request->get('title') != '') {
                $query = $query->where('title', 'like', '%' . $request->get('title') . '%');
            }
            $checkPriceFrom = $request->has('price_from') && $request->get('price_from') != 'NaN';
            $checkPriceTo = $request->has('price_to') && $request->get('price_from') != 'NaN';

            if ($checkPriceFrom || $checkPriceTo) {
                $query = $query->whereBetween('price', [$request->get('price_from'), $request->get('price_to')]);
            }

            $query->orderBy('id', "DESC");
            $products = $query->paginate($pageSize, ['*'], 'page', $page);
            return $products;
        });

        return response()->json($products);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Product;
use Illuminate\Support\Facades\Cache;
use Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redis;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect('/filter');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'title' => 'required',
            'price' => 'required|numeric',
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->messages());
        }

        $product = new Product($request->all());
        $product->save();
        Cache::flush();
        return redirect('/filter');}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layout.blade.php
<!doctype html>
<html lang="ru">
<head>
    <style>
        .demo {width: 50%;float: left;padding: 5rem 10rem;}
        .demo li {margin-bottom: 1rem;font-size: 2rem}
    </style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <!-- material icons -->
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet"
          type="text/css">

    <!-- vuetify styles -->
    <link href="https://unpkg.com/vuetify/dist/vuetify.min.css" rel="stylesheet" type="text/css">
    <link href="https://unpkg.com/vuetify/dist/vuetify.min.css" rel="stylesheet" type="text/css">

    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
            'baseUrl' => url('/'),
        ]) !!};
    </script>
</head>
<body class="">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Test</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class=""><a href="{{ route('product.index') }}">Search</a></li>
                <li><a href="{{ route('product.create') }}">Add</a></li>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="app">
    @yield('content')
</div>
<script src="{{ mix('/js/app.js') }}"></script>
<link rel="stylesheet" href="{{ mix('/css/app.css') }}">
</body>
</html>

resources/views/product/create.blade.php
@extends('layout')
@section('content')
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Create product <small>NOW</small></h3>
        </div>
        <div class="panel-body">
            <form role="form" action="{{ route('product.store') }}" method="POST">
                <div class="form-group">
                    <input type="text" name="title" id="name" class="form-control input-sm" placeholder="Title">
                    @if ($errors->get('title'))
                        <p class="alert-danger">{{ $errors->get('title')[0] }}</p>
                    @endif
                </div>
                <div class="form-group">
                    <input type="number" name="price" id="price" class="form-control input-sm" placeholder="Price">
                    @if ($errors->get('price'))
                        <p class="alert-danger">{{ $errors->get('price')[0] }}</p>
                    @endif
                </div>
                <input type="hidden" value="{{ csrf_token() }}" name="_token">

                <input type="submit" value="Create" class="btn btn-info btn-block">
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layout')

@section('content')
    <div id="app">
        <filters></filters>
    </div>
@endsection